2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:28 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:29 - connection created
2019-09-17 14:08:29 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 14:08:29 main DEBUG root:92 - Connaction Pool was created
2019-09-17 14:08:29 main DEBUG root:41 - test test 1234 - advice inserted
2019-09-17 14:08:29 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-17 14:10:12 main INFO  root:29 - connection created
2019-09-17 14:10:12 main INFO  root:29 - connection created
2019-09-17 14:10:12 main INFO  root:29 - connection created
2019-09-17 14:10:12 main INFO  root:29 - connection created
2019-09-17 14:10:12 main INFO  root:29 - connection created
2019-09-17 14:10:12 main INFO  root:29 - connection created
2019-09-17 14:10:12 main INFO  root:29 - connection created
2019-09-17 14:10:12 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:13 main INFO  root:29 - connection created
2019-09-17 14:10:14 main INFO  root:29 - connection created
2019-09-17 14:10:14 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 14:10:14 main DEBUG root:92 - Connaction Pool was created
2019-09-17 14:10:14 main DEBUG root:41 -  - advice inserted
2019-09-17 14:10:14 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-17 14:10:30 main INFO  root:29 - connection created
2019-09-17 14:10:30 main INFO  root:29 - connection created
2019-09-17 14:10:30 main INFO  root:29 - connection created
2019-09-17 14:10:30 main INFO  root:29 - connection created
2019-09-17 14:10:30 main INFO  root:29 - connection created
2019-09-17 14:10:30 main INFO  root:29 - connection created
2019-09-17 14:10:30 main INFO  root:29 - connection created
2019-09-17 14:10:30 main INFO  root:29 - connection created
2019-09-17 14:10:30 main INFO  root:29 - connection created
2019-09-17 14:10:30 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:31 main INFO  root:29 - connection created
2019-09-17 14:10:32 main INFO  root:29 - connection created
2019-09-17 14:10:32 main INFO  root:29 - connection created
2019-09-17 14:10:32 main INFO  root:29 - connection created
2019-09-17 14:10:32 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 14:10:32 main DEBUG root:92 - Connaction Pool was created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:55 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:29 - connection created
2019-09-17 14:11:56 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 14:11:56 main DEBUG root:92 - Connaction Pool was created
2019-09-17 14:11:56 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100)
2019-09-17 14:13:30 main INFO  root:29 - connection created
2019-09-17 14:13:30 main INFO  root:29 - connection created
2019-09-17 14:13:30 main INFO  root:29 - connection created
2019-09-17 14:13:30 main INFO  root:29 - connection created
2019-09-17 14:13:30 main INFO  root:29 - connection created
2019-09-17 14:13:30 main INFO  root:29 - connection created
2019-09-17 14:13:30 main INFO  root:29 - connection created
2019-09-17 14:13:30 main INFO  root:29 - connection created
2019-09-17 14:13:30 main INFO  root:29 - connection created
2019-09-17 14:13:30 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:29 - connection created
2019-09-17 14:13:31 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 14:13:31 main DEBUG root:92 - Connaction Pool was created
2019-09-17 14:13:31 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100)
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:42 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:29 - connection created
2019-09-17 14:13:43 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 14:13:43 main DEBUG root:92 - Connaction Pool was created
2019-09-17 14:13:43 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100)
2019-09-17 14:14:25 main INFO  root:29 - connection created
2019-09-17 14:14:25 main INFO  root:29 - connection created
2019-09-17 14:14:25 main INFO  root:29 - connection created
2019-09-17 14:14:25 main INFO  root:29 - connection created
2019-09-17 14:14:25 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:26 main INFO  root:29 - connection created
2019-09-17 14:14:27 main INFO  root:29 - connection created
2019-09-17 14:14:27 main INFO  root:29 - connection created
2019-09-17 14:14:27 main INFO  root:29 - connection created
2019-09-17 14:14:27 main INFO  root:29 - connection created
2019-09-17 14:14:27 main INFO  root:29 - connection created
2019-09-17 14:14:27 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 14:14:27 main DEBUG root:92 - Connaction Pool was created
2019-09-17 14:14:27 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100)
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:06:59 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:29 - connection created
2019-09-17 16:07:00 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 16:07:00 main DEBUG root:92 - Connaction Pool was created
2019-09-17 16:07:00 main DEBUG root:41 - Р‘РЈР“РђР“Рђ - advice inserted
2019-09-17 16:07:00 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:27 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:29 - connection created
2019-09-17 16:07:28 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 16:07:28 main DEBUG root:92 - Connaction Pool was created
2019-09-17 16:08:37 main INFO  root:29 - connection created
2019-09-17 16:08:37 main INFO  root:29 - connection created
2019-09-17 16:08:37 main INFO  root:29 - connection created
2019-09-17 16:08:37 main INFO  root:29 - connection created
2019-09-17 16:08:37 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:38 main INFO  root:29 - connection created
2019-09-17 16:08:39 main INFO  root:29 - connection created
2019-09-17 16:08:39 main INFO  root:29 - connection created
2019-09-17 16:08:39 main INFO  root:29 - connection created
2019-09-17 16:08:39 main INFO  root:29 - connection created
2019-09-17 16:08:39 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 16:08:39 main DEBUG root:92 - Connaction Pool was created
2019-09-17 16:08:39 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "advices_pkey"
  Detail: Key (idadvices)=(5) already exists.
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:50 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:29 - connection created
2019-09-17 16:22:51 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 16:22:51 main DEBUG root:92 - Connaction Pool was created
2019-09-17 16:22:51 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "advices_pkey"
  Detail: Key (idadvices)=(6) already exists.
2019-09-17 16:33:53 main INFO  root:29 - connection created
2019-09-17 16:33:53 main INFO  root:29 - connection created
2019-09-17 16:33:53 main INFO  root:29 - connection created
2019-09-17 16:33:53 main INFO  root:29 - connection created
2019-09-17 16:33:53 main INFO  root:29 - connection created
2019-09-17 16:33:53 main INFO  root:29 - connection created
2019-09-17 16:33:53 main INFO  root:29 - connection created
2019-09-17 16:33:53 main INFO  root:29 - connection created
2019-09-17 16:33:53 main INFO  root:29 - connection created
2019-09-17 16:33:53 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:54 main INFO  root:29 - connection created
2019-09-17 16:33:55 main INFO  root:29 - connection created
2019-09-17 16:33:55 main INFO  root:29 - connection created
2019-09-17 16:33:55 main INFO  root:29 - connection created
2019-09-17 16:33:55 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 16:33:55 main DEBUG root:92 - Connaction Pool was created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:19 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:29 - connection created
2019-09-17 16:34:20 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 16:34:20 main DEBUG root:92 - Connaction Pool was created
2019-09-17 16:34:20 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "advices_pkey"
  Detail: Key (idadvices)=(7) already exists.
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:35 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:36 main INFO  root:29 - connection created
2019-09-17 16:34:37 main INFO  root:29 - connection created
2019-09-17 16:34:37 main INFO  root:29 - connection created
2019-09-17 16:34:37 main INFO  root:29 - connection created
2019-09-17 16:34:37 main INFO  root:70 - Connection pool with 32 connections was created
2019-09-17 16:34:37 main DEBUG root:92 - Connaction Pool was created
2019-09-17 16:34:37 main DEBUG root:41 - Р‘РѕР»СЊС€Рµ РґРІРёРіР°Р№С‚РµСЃСЊ - advice inserted
2019-09-17 16:34:37 main ERROR root:43 - asdsadsadasdsadsadsda
2019-09-20 11:06:40 main INFO  root:29 - connection created
2019-09-20 11:06:40 main INFO  root:29 - connection created
2019-09-20 11:06:40 main INFO  root:29 - connection created
2019-09-20 11:06:40 main INFO  root:29 - connection created
2019-09-20 11:06:40 main INFO  root:29 - connection created
2019-09-20 11:06:40 main INFO  root:29 - connection created
2019-09-20 11:06:40 main INFO  root:29 - connection created
2019-09-20 11:06:40 main INFO  root:29 - connection created
2019-09-20 11:06:40 main INFO  root:29 - connection created
2019-09-20 11:06:40 main INFO  root:29 - connection created
2019-09-20 11:06:40 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-20 11:06:40 main DEBUG root:92 - Connaction Pool was created
2019-09-20 11:10:13 main INFO  root:29 - connection created
2019-09-20 11:10:13 main INFO  root:29 - connection created
2019-09-20 11:10:13 main INFO  root:29 - connection created
2019-09-20 11:10:13 main INFO  root:29 - connection created
2019-09-20 11:10:13 main INFO  root:29 - connection created
2019-09-20 11:10:13 main INFO  root:29 - connection created
2019-09-20 11:10:13 main INFO  root:29 - connection created
2019-09-20 11:10:13 main INFO  root:29 - connection created
2019-09-20 11:10:13 main INFO  root:29 - connection created
2019-09-20 11:10:13 main INFO  root:29 - connection created
2019-09-20 11:10:13 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-20 11:10:13 main DEBUG root:92 - Connaction Pool was created
2019-09-20 11:10:13 main ERROR root:142 - org.postgresql.util.PSQLException: ERROR: relation "advices" does not exist
  Position: 23
2019-09-20 11:10:30 main INFO  root:29 - connection created
2019-09-20 11:10:30 main INFO  root:29 - connection created
2019-09-20 11:10:30 main INFO  root:29 - connection created
2019-09-20 11:10:30 main INFO  root:29 - connection created
2019-09-20 11:10:30 main INFO  root:29 - connection created
2019-09-20 11:10:30 main INFO  root:29 - connection created
2019-09-20 11:10:30 main INFO  root:29 - connection created
2019-09-20 11:10:30 main INFO  root:29 - connection created
2019-09-20 11:10:30 main INFO  root:29 - connection created
2019-09-20 11:10:30 main INFO  root:29 - connection created
2019-09-20 11:10:30 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-20 11:10:30 main DEBUG root:92 - Connaction Pool was created
2019-09-20 11:10:30 main ERROR root:142 - org.postgresql.util.PSQLException: ERROR: relation "advices" does not exist
  Position: 23
2019-09-23 17:38:51 main INFO  root:29 - connection created
2019-09-23 17:38:51 main INFO  root:29 - connection created
2019-09-23 17:38:51 main INFO  root:29 - connection created
2019-09-23 17:38:51 main INFO  root:29 - connection created
2019-09-23 17:38:51 main INFO  root:29 - connection created
2019-09-23 17:38:51 main INFO  root:29 - connection created
2019-09-23 17:38:51 main INFO  root:29 - connection created
2019-09-23 17:38:51 main INFO  root:29 - connection created
2019-09-23 17:38:51 main INFO  root:29 - connection created
2019-09-23 17:38:52 main INFO  root:29 - connection created
2019-09-23 17:38:52 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-23 17:38:52 main DEBUG root:92 - Connaction Pool was created
2019-09-23 17:38:52 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "advices_pkey"
  Detail: Key (idadvices)=(1) already exists.
2019-09-23 17:39:18 main INFO  root:29 - connection created
2019-09-23 17:39:18 main INFO  root:29 - connection created
2019-09-23 17:39:18 main INFO  root:29 - connection created
2019-09-23 17:39:18 main INFO  root:29 - connection created
2019-09-23 17:39:18 main INFO  root:29 - connection created
2019-09-23 17:39:19 main INFO  root:29 - connection created
2019-09-23 17:39:19 main INFO  root:29 - connection created
2019-09-23 17:39:19 main INFO  root:29 - connection created
2019-09-23 17:39:19 main INFO  root:29 - connection created
2019-09-23 17:39:19 main INFO  root:29 - connection created
2019-09-23 17:39:19 main INFO  root:70 - Connection pool with 10 connections was created
2019-09-23 17:39:19 main DEBUG root:92 - Connaction Pool was created
2019-09-23 17:39:19 main ERROR root:46 - org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "advices_pkey"
  Detail: Key (idadvices)=(2) already exists.
2019-09-23 18:04:49 main ERROR root:31 - Wrong create connection
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:04:49 main ERROR root:66 - Wrong initialize connection pool
by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong create connection
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:32)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:04:49 main FATAL root:51 - by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong initialize connection pool
2019-09-23 18:05:43 main ERROR root:31 - Wrong create connection
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:05:43 main ERROR root:66 - Wrong initialize connection pool
by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong create connection
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:32)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:05:43 main FATAL root:51 - by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong initialize connection pool
2019-09-23 18:06:20 main ERROR root:31 - Wrong create connection
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:06:20 main ERROR root:66 - Wrong initialize connection pool
by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong create connection
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:32)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
2019-09-23 18:06:20 main FATAL root:51 - by.epam.crackertracker.exception.TrackerConnectionPoolException: Wrong initialize connection pool
2019-09-23 18:07:06 main ERROR root:31 - Wrong create connection
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:138)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at by.epam.crackertracker.creator.ConnectionCreatorTrackerJdbc.newConnection(ConnectionCreatorTrackerJdbc.java:28)
	at by.epam.crackertracker.pool.ConnectionPool.init(ConnectionPool.java:62)
	at by.epam.crackertracker.pool.ConnectionPool.<init>(ConnectionPool.java:49)
	at by.epam.crackertracker.pool.ConnectionPool.getInstance(ConnectionPool.java:90)
	at by.epam.crackertracker.dao.AdviceDaoJdbcImpl.insert(AdviceDaoJdbcImpl.java:35)
	at by.epam.crackertracker.dao.AdviceDaoJdbcTest.testInsert(AdviceDaoJdbcTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 40 more
